codepkg/objects/ZPAPER__zStack__c.object
<CustomObject>
    <description>Force.com binding record for zPaper content
from, pages and normal workflow fields
picklist for doctype(program classification) and channel (fax,email,data,scan,file,SMS)
parent stack lookup
TODO: received, split who/when, attached who/when, data entry who/when
            var triageModifiedBy = getSFField(doc, zData.zps, &quot;Triage_Started_By__c&quot;, null, zStackId);
            arrOfPairs.push(&quot;Triage_Started_By__c&quot;, doc.kbData.remoteUser);
            arrOfPairs.push(&quot;Triage_Started_At__c&quot;, formatNow);
        zData.zp+&quot;Triage_Status__c&quot;,&quot;Locked by &quot; + doc.kbData.remoteUser);</description>
    <fields>
        <fullName>ZPAPER__Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Weekend</fullName>
                </value>
                <value>
                    <fullName>After Hours</fullName>
                </value>
                <value>
                    <fullName>Slow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>zStack</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>zStack Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>zStacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/zAcceptControllerTests.cls
@isTest
public class zAcceptControllerTests {
    public static ZPAPER__zStack__c stack;
    public static User usr;
    
    static void init() {
        Profile pf = [Select Id from Profile where Name = 'Standard User'];
        usr = new User();
        usr.FirstName = 'Test1';
        usr.LastName = 'User1';
        usr.Email = 'testuser1@test123456789.com';
        usr.CompanyName = 'test.com';
        usr.Title = 'Test User';
        usr.Username = 'testuser1@test123456789.com';
        usr.Alias = 'testuse1';
        usr.CommunityNickname = 'Test_User1';
        usr.TimeZoneSidKey = 'America/Mexico_City';
        usr.LocaleSidKey = 'en_US';
        usr.EmailEncodingKey = 'ISO-8859-1';
        usr.ProfileId = pf.Id;
        usr.LanguageLocaleKey = 'en_US';
        insert usr;
        
        stack = new ZPAPER__zStack__c(ZPAPER__Priority__c = 'Normal');
        insert stack;
    }
    
    @isTest
    private static void testChangeOwner() {
        init();
        Test.startTest();
        System.runAs(usr) {
            ZPAPER__zStack__c curStack = [select Id,OwnerId from ZPAPER__zStack__c where Id = :stack.Id];
            Id curOwnerId = curStack.OwnerId;
            System.debug('@@@ Original owner: ' + curOwnerId);
            List<ZPAPER__zStack__c> stackList = new List<ZPAPER__zStack__c>();
            stackList.add(curStack);
            ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(stackList);
            stdSetController.setSelected(stackList);
            zAcceptController controller = new zAcceptController(stdSetController);
            PageReference pageRef = controller.setOwnerAndRedirect();
            System.assert(NULL != pageRef);
            curStack = [select Id,OwnerId from ZPAPER__zStack__c where Id = :stack.Id];
            System.debug('@@@ New owner: ' + curStack.OwnerId);
            System.assertNotEquals(curOwnerId, curStack.OwnerId);
        }
        Test.stopTest();
    }
}